### ISSUE TITLE
schematic for CH552 download adapter?

### ISSUE THREAD

**Issue by charkster** [sohtamei/docs#2]
Do you have a schematic for the CH552 download adapter? I can't order one from kadenken.com
Will it work for the Tang Nano?
Thank you.

**Comment by charkster** [comment]
I put a 22k ohm resistor from the Tang Nano 3.3V pin to the USB D+ pin and was able to program the CH552 on the Tang Nano. I did not need to make 3.3V from the USB's 5V because the Tang Nano has a 3.3V regulator from the USB's 5V.

**Comment by sohtamei** [comment]
Thanks for your report, so much !
Just FYI, The shecmatic of adapter is following,
![schematics](https://user-images.githubusercontent.com/43091864/162562264-9cc13538-d35f-45b0-9152-df374681c72c.png)

**Comment by charkster** [comment]
@sohtamei I will try these values to see if they program the Tang Nano. Thanks for the schematic.
